# User env variable DBPASSWD as password

version: "3.1"

services:
  mongo:
    image: "mongo:latest"
    container_name: "mongodb"
    restart: unless-stopped
    hostname: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MGPASSWD}
    volumes:
      - /srv/mongodb/db:/data/db
    ports:
      - "27017-27019:27017-27019"